import { useState, useRef, useEffect } from "react";
import EmojiPicker from "emoji-picker-react";

import { motion, AnimatePresence } from "framer-motion";

import MainLayout from "../layouts/MainLayout";
import ChatBubble from "../components/ChatBubble";
import TypingIndicator from "../components/TypingIndicator";

import {
  Bot,
  Send,
  Menu,
  X,
  Trash2,
  Clock3,
  MessageSquare,
  Paperclip,
  Smile,
  Mic,
} from "lucide-react";

interface ChatMessage {
  role: "user" | "assistant";
  message: string;
}

export default function Chat() {

  /* ===========================
      States
  =========================== */

  const [messages, setMessages] =
    useState<ChatMessage[]>([
      {
        role: "assistant",
        message:
          "Hello! 👋 I'm your AI Customer Support Assistant. Ask me anything from the company knowledge base.",
      },
    ]);

  const [input, setInput] = useState("");

  const [loading, setLoading] =
    useState(false);

  const [streamingMessage, setStreamingMessage] =
    useState("");

  const [showSidebar, setShowSidebar] =
    useState(false);

  const [showEmojiPicker, setShowEmojiPicker] =
    useState(false);

  const [attachedFile, setAttachedFile] =
    useState<File | null>(null);

  const [showSuggestions, setShowSuggestions] =
    useState(true);

  /* ===========================
      Refs
  =========================== */

  const messagesEndRef =
    useRef<HTMLDivElement>(null);

  const textareaRef =
    useRef<HTMLTextAreaElement>(null);

  const fileInputRef =
    useRef<HTMLInputElement>(null);

  const emojiRef =
    useRef<HTMLDivElement>(null);

  /* ===========================
      Suggested Questions
  =========================== */

  const suggestions = [
    "What is the company refund policy?",
    "How do I reset my password?",
    "Explain the onboarding process",
    "Where can I contact support?",
    "Tell me about employee benefits",
    "Explain leave policy",
  ];

  /* ===========================
      Auto Scroll
  =========================== */

  useEffect(() => {

    messagesEndRef.current?.scrollIntoView({
      behavior: "smooth",
    });

  }, [
    messages,
    streamingMessage,
    loading,
  ]);

  /* ===========================
      Auto Expand Textarea
  =========================== */

  useEffect(() => {

    if (!textareaRef.current) return;

    textareaRef.current.style.height =
      "auto";

    textareaRef.current.style.height =
      textareaRef.current.scrollHeight + "px";

  }, [input]);

  /* ===========================
      handle click emoji picker
  =========================== */

  useEffect(() => {
    function handleClick(e: MouseEvent) {
      if (
        emojiRef.current &&
        !emojiRef.current.contains(e.target as Node)
      ) {
        setShowEmojiPicker(false);
      }
    }

    document.addEventListener("mousedown", handleClick);

    return () =>
      document.removeEventListener("mousedown", handleClick);
  }, []);

  /* ===========================
      Fake AI Streaming
  =========================== */

  const streamAIResponse = (
    text: string
  ) => {

    let index = 0;

    setStreamingMessage("");

    const interval = setInterval(() => {

      index++;

      setStreamingMessage(
        text.slice(0, index)
      );

      if (index >= text.length) {

        clearInterval(interval);

        setMessages((prev) => [
          ...prev,
          {
            role: "assistant",
            message: text,
          },
        ]);

        setStreamingMessage("");

        setLoading(false);

      }

    }, 18);

  };

  /* ===========================
      Send Message
  =========================== */

  const sendMessage = () => {

    if (!input.trim()) return;

    const userMessage = input;

    setMessages((prev) => [
      ...prev,
      {
        role: "user",
        message: userMessage,
      },
    ]);

    setInput("");

    setAttachedFile(null);

    if (fileInputRef.current) {
      fileInputRef.current.value = "";
    }

    setLoading(true);

    setShowSuggestions(false);

    setTimeout(() => {

      streamAIResponse(
        "This response is currently mocked. Later it will be generated by your RAG pipeline using retrieved company knowledge and an LLM. Streaming animation already simulates real AI typing."
      );

    }, 500);

  };

  /* ===========================
      handle file upload in attachment
  =========================== */

  const handleFileUpload = (
    e: React.ChangeEvent<HTMLInputElement>
  ) => {
    const file = e.target.files?.[0];

    if (!file) return;

    setMessages((prev) => [
      ...prev,
      {
        role: "user",
        message: `📎 Uploaded: ${file.name}`,
      },
    ]);

    console.log(file);

    e.target.value = "";
  };
  /* ===========================
      Clear Chat
  =========================== */

  const clearChat = () => {

    setMessages([
      {
        role: "assistant",
        message:
          "Chat cleared successfully. How can I help you today?",
      },
    ]);

    setShowSuggestions(true);

  };

  return (

    <MainLayout>

      {/* =======================================
              PAGE HEADER
      ======================================== */}

      <div className="mb-6">

        <h1
          className="
            text-3xl
            lg:text-4xl
            font-bold
            text-slate-900
            dark:text-white
          "
        >
          AI Customer Support Chat
        </h1>

        <p
          className="
            mt-2
            text-slate-500
            dark:text-slate-400
          "
        >
          Chat with your AI assistant powered by
          Retrieval-Augmented Generation.
        </p>

      </div>

      {/* =======================================
              MAIN LAYOUT
      ======================================== */}

      <div
        className="
          relative

          flex

          gap-6

          h-[calc(100vh-170px)]
        "
      >
        {/* ===========================
            Mobile Overlay
        =========================== */}

        <AnimatePresence>

          {showSidebar && (

            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}

              onClick={() => setShowSidebar(false)}

              className="
                fixed
                inset-0

                bg-black/40
                backdrop-blur-sm

                z-40

                xl:hidden
              "
            />

          )}

        </AnimatePresence>

        {/* ===========================
            Sidebar
        =========================== */}

        <motion.aside

          initial={{
            x: -80,
            opacity: 0,
          }}

          animate={{
            x: 0,
            opacity: 1,
          }}

          transition={{
            duration: 0.35,
          }}

          className={`
            fixed
            xl:static

            top-0
            left-0

            h-full
            xl:h-auto

            w-[300px]
            xl:w-80

            z-50

            rounded-none
            xl:rounded-3xl

            border
            border-white/30
            dark:border-slate-700

            bg-white/75
            dark:bg-slate-900/75

            backdrop-blur-2xl

            shadow-2xl

            transition-transform
            duration-300

            ${showSidebar
              ? "translate-x-0"
              : "-translate-x-full xl:translate-x-0"
            }
          `}
        >

          {/* Sidebar Header */}

          <div
            className="
              flex
              items-center
              justify-between

              p-6

              border-b
              border-slate-200
              dark:border-slate-700
            "
          >

            <div className="flex items-center gap-3">

              <div
                className="
                  h-11
                  w-11

                  rounded-2xl

                  flex
                  items-center
                  justify-center

                  bg-gradient-to-r
                  from-blue-600
                  to-indigo-600

                  text-white
                "
              >
                <MessageSquare size={22} />
              </div>

              <div>

                <h2
                  className="
                    font-bold
                    text-slate-900
                    dark:text-white
                  "
                >
                  Recent Chats
                </h2>

                <p
                  className="
                    text-xs
                    text-slate-500
                  "
                >
                  Conversation history
                </p>

              </div>

            </div>

            <button
              onClick={() =>
                setShowSidebar(false)
              }
              className="
                xl:hidden

                p-2

                rounded-xl

                hover:bg-slate-100
                dark:hover:bg-slate-800

                transition
              "
            >
              <X size={20} />
            </button>

          </div>

          {/* Chat List */}

          <div
            className="
              flex-1

              overflow-y-auto

              p-5

              space-y-3
            "
          >

            {[
              "Company Policies",
              "Product Information",
              "Support FAQs",
              "HR Guidelines",
              "Technical Support",
            ].map((chat, index) => (

              <motion.button

                key={chat}

                whileHover={{
                  x: 4,
                }}

                whileTap={{
                  scale: 0.98,
                }}

                className="
                  w-full

                  text-left

                  rounded-2xl

                  border
                  border-transparent

                  bg-white/60
                  dark:bg-slate-800/70

                  hover:border-blue-300
                  dark:hover:border-blue-700

                  hover:bg-blue-50
                  dark:hover:bg-slate-700

                  p-4

                  transition-all
                "
              >

                <div
                  className="
                    font-semibold
                    text-slate-900
                    dark:text-white
                  "
                >
                  {chat}
                </div>

                <div
                  className="
                    mt-1

                    text-xs

                    text-slate-500
                    dark:text-slate-400
                  "
                >
                  Conversation #{index + 1}
                </div>

              </motion.button>

            ))}

          </div>

          {/* Footer */}

          <div
            className="
              border-t
              border-slate-200
              dark:border-slate-700

              p-5
            "
          >

            <div
              className="
                flex
                items-center
                gap-2

                text-sm

                text-slate-500
                dark:text-slate-400
              "
            >

              <Clock3 size={16} />

              Chat history is saved locally.

            </div>

          </div>

        </motion.aside>

        {/* ===========================
            MAIN CHAT AREA
        =========================== */}

        <motion.section

          initial={{
            opacity: 0,
            y: 20,
          }}

          animate={{
            opacity: 1,
            y: 0,
          }}

          transition={{
            duration: 0.4,
          }}

          className="
            flex-1

            flex
            flex-col

            overflow-hidden

            rounded-3xl

            border
            border-white/30
            dark:border-slate-700

            bg-white/70
            dark:bg-slate-900/70

            backdrop-blur-2xl

            shadow-2xl
          "
        >
          {/* ===========================
              CHAT HEADER
          =========================== */}

          <div
            className="
              flex
              items-center
              justify-between

              px-5
              py-4

              border-b
              border-slate-200
              dark:border-slate-700

              bg-white/50
              dark:bg-slate-900/40

              backdrop-blur-xl
            "
          >

            <div className="flex items-center gap-4">

              <button
                onClick={() => setShowSidebar(true)}
                className="
                  xl:hidden

                  p-2

                  rounded-xl

                  hover:bg-slate-200
                  dark:hover:bg-slate-700

                  transition
                "
              >
                <Menu size={22} />
              </button>

              <div
                className="
                  h-14
                  w-14

                  rounded-2xl

                  flex
                  items-center
                  justify-center

                  bg-gradient-to-r
                  from-blue-600
                  via-indigo-600
                  to-purple-600

                  text-white

                  shadow-lg
                "
              >

                <Bot size={28} />

              </div>

              <div>

                <h2
                  className="
                    text-xl
                    font-bold

                    text-slate-900
                    dark:text-white
                  "
                >
                  AI Assistant
                </h2>

                <div
                  className="
                    flex
                    items-center
                    gap-2

                    mt-1
                  "
                >

                  <span
                    className="
                      h-2.5
                      w-2.5

                      rounded-full

                      bg-green-500

                      animate-pulse
                    "
                  />

                  <span
                    className="
                      text-sm
                      text-green-600
                      dark:text-green-400
                    "
                  >
                    Online
                  </span>

                </div>

              </div>

            </div>

            <button
              onClick={clearChat}
              className="
                flex
                items-center
                gap-2

                rounded-xl

                bg-red-500
                hover:bg-red-600

                text-white

                px-5
                py-3

                transition-all
                duration-200

                hover:scale-105
              "
            >

              <Trash2 size={18} />

              <span className="hidden sm:block">
                Clear Chat
              </span>

            </button>

          </div>

          {/* ===========================
              Suggested Questions
          =========================== */}

          <AnimatePresence>

            {showSuggestions && (

              <motion.div

                initial={{
                  opacity: 0,
                  height: 0,
                }}

                animate={{
                  opacity: 1,
                  height: "auto",
                }}

                exit={{
                  opacity: 0,
                  height: 0,
                }}

                transition={{
                  duration: 0.25,
                }}

                className="
                  overflow-hidden

                  border-b
                  border-slate-200
                  dark:border-slate-700

                  bg-slate-50/70
                  dark:bg-slate-900/30
                "
              >

                <div
                  className="
                    flex

                    gap-3

                    overflow-x-auto

                    px-5
                    py-4

                    scrollbar-hide
                  "
                >

                  {suggestions.map((item) => (

                    <motion.button

                      key={item}

                      whileHover={{
                        y: -2,
                        scale: 1.03,
                      }}

                      whileTap={{
                        scale: 0.98,
                      }}

                      onClick={() => setInput(item)}

                      className="
                        flex-shrink-0

                        rounded-full

                        border
                        border-slate-200
                        dark:border-slate-700

                        bg-white
                        dark:bg-slate-800

                        px-4
                        py-2.5

                        text-sm

                        whitespace-nowrap

                        hover:bg-blue-50
                        dark:hover:bg-slate-700

                        transition-all
                      "
                    >

                      {item}

                    </motion.button>

                  ))}

                </div>

              </motion.div>

            )}

          </AnimatePresence>

          {/* ===========================
              MESSAGES AREA
          =========================== */}

          <div
            className="
              flex-1

              overflow-y-auto

              px-5
              py-6

              bg-gradient-to-b
              from-slate-50
              via-white
              to-slate-50

              dark:from-slate-950
              dark:via-slate-900
              dark:to-slate-950

              space-y-6
            "
          >
            {messages.map((msg, index) => (

              <motion.div
                key={index}
                initial={{
                  opacity: 0,
                  y: 20,
                }}
                animate={{
                  opacity: 1,
                  y: 0,
                }}
                transition={{
                  duration: 0.25,
                }}
              >

                <ChatBubble
                  role={msg.role}
                  message={msg.message}
                />

              </motion.div>

            ))}

            {loading && (

              <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
              >

                <TypingIndicator />

              </motion.div>

            )}

            <div ref={messagesEndRef} />

          </div>

          {/* ======================================
                  INPUT SECTION
          ====================================== */}

          <div
            className="
              sticky
              bottom-0

              border-t
              border-slate-200
              dark:border-slate-700

              bg-white/70
              dark:bg-slate-900/70

              backdrop-blur-2xl

              px-4
              py-4

              pb-[calc(env(safe-area-inset-bottom)+16px)]
            "
          >

            {/* Input Box */}

            <input
              ref={fileInputRef}
              type="file"
              className="hidden"
              accept=".pdf,.doc,.docx,.txt,.png,.jpg,.jpeg,.webp"

              onChange={(e) => {
                if (e.target.files?.length) {
                  setAttachedFile(e.target.files[0]);
                }
              }}
            />

            {attachedFile && (

              <div
                className="
                mb-4

                flex
                items-center
                justify-between

                rounded-2xl

                border
                border-slate-200
                dark:border-slate-700

                bg-slate-50
                dark:bg-slate-800

                px-4
                py-3

                shadow-sm
                "
              >

                <div className="flex items-center gap-3">

                  <Paperclip
                    size={18}
                    className="text-blue-600"
                  />

                  <div>

                    <p className="font-medium text-slate-900 dark:text-white">
                      {attachedFile.name}
                    </p>

                    <p className="text-xs text-slate-500 dark:text-slate-400">
                      {(attachedFile.size / 1024).toFixed(1)} KB
                    </p>

                  </div>

                </div>

                <button
                  onClick={() => setAttachedFile(null)}
                  className="
                  text-red-500
                  hover:text-red-600
                  text-sm
                  font-medium
                  transition
                  "
                >
                  Remove
                </button>

              </div>

            )}
            <div
              className="
                flex
                items-end

                gap-3

                rounded-3xl

                border
                border-slate-200
                dark:border-slate-700

                bg-white
                dark:bg-slate-800

                px-4
                py-3

                shadow-xl
              "
            >

              {/* Attachment */}

              <button
                onClick={() => fileInputRef.current?.click()}

                className="
                h-11
                w-11

                rounded-xl

                flex
                items-center
                justify-center

                hover:bg-slate-100
                dark:hover:bg-slate-700

                transition
                "
              >

                <Paperclip size={20} />

              </button>

              {/* Textarea */}

              <textarea
                ref={textareaRef}

                value={input}

                onChange={(e) =>
                  setInput(e.target.value)
                }

                onKeyDown={(e) => {
                  if (
                    e.key === "Enter" &&
                    !e.shiftKey
                  ) {
                    e.preventDefault();
                    sendMessage();
                  }
                }}

                placeholder="Ask anything about your company..."

                className="
                  flex-1

                  resize-none

                  min-h-[26px]
                  max-h-[180px]

                  overflow-y-auto

                  bg-transparent

                  outline-none

                  text-slate-900
                  dark:text-white

                  placeholder:text-slate-400
                "
              />

              {/* Emoji */}

              <div className="relative" ref={emojiRef}>

                <button
                  onClick={() =>
                    setShowEmojiPicker((prev) => !prev)
                  }
                  className="
                  h-11
                  w-11
                  rounded-xl
                  flex
                  items-center
                  justify-center
                  hover:bg-slate-100
                  dark:hover:bg-slate-700
                  transition
                  "
                >
                  <Smile size={20} />
                </button>

                {showEmojiPicker && (
                  <div
                    className="
                    absolute
                    bottom-14
                    left-0
                    z-50
                    "
                  >
                    <EmojiPicker
                      onEmojiClick={(emojiData) => {
                        setInput(
                          (prev) => prev + emojiData.emoji
                        );
                      }}
                    />
                  </div>
                )}

              </div>

              {/* Voice */}

              <button
                className="
                  p-2.5

                  rounded-xl

                  hover:bg-slate-100
                  dark:hover:bg-slate-700

                  transition
                "
              >
                <Mic
                  size={20}
                  className="text-slate-500"
                />
              </button>

              {/* Send */}

              <motion.button

                whileHover={{
                  scale: 1.05,
                }}

                whileTap={{
                  scale: 0.95,
                }}

                onClick={sendMessage}

                disabled={loading}

                className="
                  h-12
                  w-12

                  rounded-2xl

                  flex
                  items-center
                  justify-center

                  bg-gradient-to-r
                  from-blue-600
                  to-indigo-600

                  text-white

                  shadow-lg

                  disabled:opacity-50
                  disabled:cursor-not-allowed
                "
              >

                <Send size={20} />

              </motion.button>

            </div>

            {/* Footer */}

            <div
              className="
                mt-3

                flex
                flex-col
                sm:flex-row

                justify-between

                gap-2

                text-xs

                text-slate-500
                dark:text-slate-400
              "
            >

              <span>
                {messages.length} Messages
              </span>

              <span>
                Press Enter to send • Shift + Enter for new line
              </span>

            </div>

          </div>

        </motion.section>

      </div>

    </MainLayout>

  );

}